### ISSUE TITLE
Question, how do I search within bound or radius?

### ISSUE THREAD

**Issue by trsh** [plopgrizzly/ami#3]
I looked into the doc & code, and could not figure out.

**Comment by AldaronLau** [comment]
@trsh I haven't touched / looked at this project in a while, and I don't believe it was completed, but you should be able use `BBox::collide()`, getting the `BBox` from the `Collider` trait.  You can check from center with `BBox::center()` and vector subtraction followed by `Vector::length()` to get distance from an object.  I think the idea was to add search methods on `Octree`, but currently they would have to be written by hand with above mentioned methods, and possibly not as performant as they could be.
